//
// Created by Rodion Shyshkin on 19.12.2020.
//

#ifndef COMPSHOP_SRC_CLI_STATES_COMMAND_STATES_PERSISTTYPE_H_
#define COMPSHOP_SRC_CLI_STATES_COMMAND_STATES_PERSISTTYPE_H_

enum class PersistType {
  SAVE,
  LOAD
};

#endif //COMPSHOP_SRC_CLI_STATES_COMMAND_STATES_PERSISTTYPE_H_
