//
// Created by Rodion Shyshkin on 11.12.2020.
//

#ifndef COMPSHOP_SRC_CORE_COMPONENTTYPE_H_
#define COMPSHOP_SRC_CORE_COMPONENTTYPE_H_

enum class ComponentType {
  UNKNOWN,
  MOTHERPLATE,
  PROCCESSOR,
  HARDDISK,
  GRAPHICSCARD,
  RAM
};

#endif //COMPSHOP_SRC_CORE_COMPONENTTYPE_H_
