//
// Created by Rodion Shyshkin on 18.12.2020.
//

#ifndef COMPSHOP_SRC_CLI_STATES_STATETYPE_H_
#define COMPSHOP_SRC_CLI_STATES_STATETYPE_H_

enum class StateType {
  UNKNOWN_STATE,

  MAIN_MENU,
  ADD_COMPONENT,
  ADD_WORKER,
  SHOW_COMPONENT,
  SHOW_WORKER,
  SHOW_COMPONENTS_LIST,
  SHOW_WORKERS_LIST,
  REMOVE_COMPONENT,
  REMOVE_WORKER,

  SAVE_TO_FILE,
  LOAD_FROM_FILE,

  EXIT_STATE
};

#endif //COMPSHOP_SRC_CLI_STATES_STATETYPE_H_
